### ISSUE TITLE
Build for x86 64-bit Xojo 2015r3

### ISSUE THREAD

**Issue by spaceprograms** [macoslib/macoslib#194]
If you open Macoslib in Xojo 2015r3, switch the Architecture to x86 64-bit, then try to build the app. The compiler throws up loads of errors relating to Ptr, Integer and Type mismatch.

This is an FYI as I unfortunately don't have the time to help fix these at the moment.

**Comment by jda1** [comment]
This is still true. I'm guessing that there will be no effort made to converting MacOSLib to 64-bit (it's a big project and certainly beyond my capabilities), but before I go through the 50+ MacOSLib errors that my project throws with 64-bit enabled and try to see if I can fix them one at a time, I thought I'd ask. Even if MacOSLib is now a lame duck, I do want to say that I am grateful to everyone who contributed to it, it has been incredibly useful.

**Comment by vidalvanbergen** [comment]
There was some talk about making a macoslib addon some time back, but I haven't heard much from it since:
https://forum.xojo.com/22186-macoslib-future/

**Comment by jda1** [comment]
I'd like to revisit this. I'd love to go 64-bit but the biggest problem is that I probably have hundreds of calls to MacOSLib. I don't have the knowledge to convert the methods to 64-bit (I tried, but abjectly failed). But I'm willing to be a worker bee if someone (Thomas?) would provide generic information and examples of what has to be done. 64 bit is the future, and MacOSLib will fall off the map if it isn't updated.

**Comment by vidalvanbergen** [comment]
I would like to see this too, if there's any way I can help?

**Comment by tempelmann** [comment]
AFAIK, there are two different things that need doing:

1. Make sure all parameters and structures fit on both 32 and 64 bit builds. Usually, for parameters, this should need no work, because usually an "Integer" type will fit that need. More work are structures and peeking into memoryblocks for arrays and such. A while back, a SizeOfInteger constant was added that can be used to calculate array offset for this task.

2. Identify the calls do not work at all in 64 bit any more. That's the case for some old, deprecated, stuff. I guess all the QT... stuf falls into this category.

I'd think that most of the low level classes, e.g. those in CoreFoundation and in Cocoa modules, should already work on 64 bit. It remains to be found out what doesn't work and then someone updates them. There's no magic to it, just manual labor :)

So, jda, if you start listing the stuff that does not work, then you and others can focus on those first.

**Comment by tempelmann** [comment]
For instructions, it's simple:

For every declare, find the original documentation (using Apple developer website or the header .h files), see which parameters are used, and make sure the same type is used on the declare. E.g, if the type is UIn32, then you need to match that even on 64 bit. If it's UInteger, match that, too.
Same goes for structures.
And for ascess into memoryblocks, see the code where SizeOfInteger is used as an example, and make sure it's used everywhere that way.
Oh, and if you want to restrict macoslib to compile only with very recent Xojo versions, use the newly introduced CGFloat type for where now a single type is used, matching what the Apple docs use. CGFloat has to be a Double on 64 bit and a Single on 32 bit. Before Xojo added this type, you could not do that in Xojo code. Understand what I mean?

**Comment by jda1** [comment]
Thanks, Thomas. If you don't mind I'll post some examples of things that don't compile in MacOSLib and my proposed solution.

**Comment by vidalvanbergen** [comment]
Can we use #if target32bit/target64bit in order to keep MacOSLib backward compatible? I can confirm that those two targets are available at least as far back as Real Studio 2012.2.1

**Comment by tempelmann** [comment]
Vidal, not for CGFloats, for everything else it's already done extensively in the code.

**Comment by jda1** [comment]
Personally, I would have no problem with a fork of MacOSLib for 64 bit that required Xojo 2016R1 (or whichever implemented CGFloat.

Thomas, here's my first question, and it involves your CertTools module.

declare function ASN1_get_object lib "/usr/lib/libcrypto.dylib" (ByRef pp as Ptr, ByRef plength as Int32, ByRef ptag as Int32, ByRef pclass as Int32, omax as Int32) as Int32
    
gives the build error:

![xojoscreensnapz001](https://cloud.githubusercontent.com/assets/6324851/17444161/89c97a9c-5b0c-11e6-8935-f64f589266e8.png)

What would the fix look like? Once I know I can apply it to all instances where this occurs.

**Comment by tempelmann** [comment]
Oh, great. Now we also have to deal with Xojo compiler issues.

Apparently, Xojo won't downgrade an Int64 to a Int32. Try using a tmp variable in which you assign the "e-p" result to a Int32 or UInt32, then pass that to the function.

**Comment by jda1** [comment]
I was able to get around that particular error with this

    dim res, type, xclass, length as Int32
    
But now of course I get these errors

![xojoscreensnapz001](https://cloud.githubusercontent.com/assets/6324851/17444814/07143df4-5b10-11e6-81f5-a7bea5649b96.png)

I'm simply building the current version of MacOSLib as 64-bit. Do you have the time to do this? I think you'll recognize the problems more quickly that way.

**Comment by tempelmann** [comment]
If you change the type of a variable, e.g. like "Ptr(...)", the variable and the type have to have the same size. So, assign "length" to a Int64, then you can cast it to Ptr, I believe.

And no, I have neiter time nor interest in doing this myself. I don't need 64 bit support right now, and I have my own work. Only exception, currently: If someone pays me by the hour ($100/h) for doing it (I'm not young any more and I need the money ;)

But that's why it's open source - so that people can do it themselves.

Maybe ask in the forum for help with these things. It's only a few complications, and once you know how to fix them, the rest should be easy.

**Comment by jda1** [comment]
I didn't mean if you had time to do the conversion -- I already said that I'd do it (and vidal has volunteered as well). But we need advice to get it right. That's all.

**Comment by tempelmann** [comment]
Then better ask on the forum. There are more people there that know more about this than I do because they probably already tried more.

**Comment by vidalvanbergen** [comment]
Thanks to Serge, Initial support for 64bit is now available in macoslib, you can find it here:
https://github.com/vidalvanbergen/macoslib/tree/master-64bit
Please note that you can't build for 32bit systems with this fork, 32bit & 64bit fork are kept separate for backwards compatibility.
