### ISSUE TITLE
Referencing a NSToolbarButtonItem

### ISSUE THREAD

**Issue by jaspham** [macoslib/macoslib#198]
I have asked on the Xojo forum but I have gotten no responses.

I have successfully implemented macoslib's NSToolbar in my current project. However, I am having trouble referring back to a NSToolbarButtonItem. I reference all the toolbar items in my window open event, and in my ToolbarAction event, I am trying to do it so that the image of an item changes after it is pressed.

Here is my code (I've tried out different things, not all in the same instance):
Test 1.       NSToolbarButtonItem.tag(5).Image = MacIcon.NewIconFromOSInfo(MacIcon.kUnlockedIcon)
Test 2.       Dim okb As NSToolbarButtonItem("GroupToolbarItem")
Test 2 (continued).       okb.Image = MacIcon.NewIconFromOSInfo(MacIcon.kUnlockedIcon)
Test 3.      NSToolbarItem(identifier.) = MacIcon.NewIconFromOSInfo(MacIcon.kUnlockedIcon)
Test 4.       groupicon.Image = MacIcon.NewIconFromOSInfo(MacIcon.kUnlockedIcon)

Can anyone with experience of macoslib help with this?

**Comment by vidalvanbergen** [comment]
I think you'll need to iterate through each NSToolbarItem until you find one with the identifier you want to change, after that it's simply a matter of setting the image.

  for each item as NSToolbarItem in ToolbarMain.Items
    if item.ItemIdentifier = Identifier then
      item.Image = NSImage.LockUnlockedTemplate
    end if
  next

As in the example, you might want to switch to NSImage.someiconname, since MacIcon uses carbonlib, as carbon is probably not future proof with Apple phasing it out eventually.

**Comment by jaspham** [comment]
Ok. Thanks!
